//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportProfile
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public string ConsumerNo { get; set; }
        public string RegionCode { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string IsAdmin { get; set; }
        public int Login_ID { get; set; }
        public int ID { get; set; }
    }
}
