//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportError
    {
        public string ErrorLevel { get; set; }
        public string ColumnName { get; set; }
        public string ErrorMessage { get; set; }
        public int ID { get; set; }
    }
}
