//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBillHistory
    {
        public int ID { get; set; }
        public System.DateTime BillDate { get; set; }
        public int UnitsConsumed { get; set; }
        public int BillAmount { get; set; }
        public bool Paid { get; set; }
        public Nullable<int> Consumer_ID { get; set; }
        public System.DateTime BillPaidDate { get; set; }
        public bool IsPdfGenerated { get; set; }
    
        public virtual tblConsumer tblConsumer { get; set; }
    }
}
