//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPaymentDetail
    {
        public int ID { get; set; }
        public int ConsumerNo { get; set; }
        public string ConsumerName { get; set; }
        public string Address { get; set; }
        public int BillAmount { get; set; }
        public int UnitsConsumed { get; set; }
        public bool Paid { get; set; }
        public System.DateTime BillDate { get; set; }
        public int Login_ID { get; set; }
        public int Consumer_ID { get; set; }
    }
}
