//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vUnitsConsumption
    {
        public string Year { get; set; }
        public Nullable<int> UnitsConsumed { get; set; }
        public int Consumer_ID { get; set; }
        public long ID { get; set; }
    }
}
